"""OpenRouter LLM client for Mapping's genuinely-agentic judgment calls.

This is the *only* place an LLM gets called anywhere in this pipeline.
Discovery never calls it (single-schema structural checks are plain code).
Mapping's deterministic paths (schema-declared relations, exact numeric
value matches, exact vocabulary string matches) never call it either — only
the two free-text/ambiguous-naming cases do.

`call_count` is a plain module-level counter, not clever — it exists solely
so run.py can assert "zero LLM calls on the cached second run" without
having to mock anything.
"""

from __future__ import annotations

import json

from openai import OpenAI

from .config import OPENROUTER_API_KEY, OPENROUTER_BASE_URL, OPENROUTER_MODEL

call_count = 0

_client = OpenAI(base_url=OPENROUTER_BASE_URL, api_key=OPENROUTER_API_KEY or "missing")

JUDGMENT_SYSTEM_PROMPT = """\
You are the Mapping agent's judgment step in a content-migration tool. You \
are given a piece of evidence from a WordPress site and a short list of \
candidate entries from a separate Strapi catalog that a cheap heuristic \
thinks *might* be related. Your job is to decide, honestly, whether the \
evidence actually corresponds to exactly one candidate.

It is entirely acceptable — and expected in some cases — to conclude there \
is no real match, or that you are not confident enough to decide and a \
human should look at it. Do not force a match just because candidates were \
provided; the candidate list was generated by a loose keyword heuristic and \
may be entirely spurious.

Respond with ONLY a JSON object, no prose, no markdown fences:
{
  "decision": "match" | "no_match" | "escalate",
  "matched_ref": "<ref of the matching candidate, or null>",
  "matched_content_type": "<content_type of the matching candidate, or null>",
  "confidence": <float 0.0-1.0>,
  "reasoning": "<one or two sentences>"
}
"""


def judge(evidence: str, candidates: list[dict]) -> dict:
    """Ask the LLM to adjudicate `evidence` against `candidates`.

    `candidates` is a list of {"content_type": ..., "ref": ..., "label": ...}
    dicts — enough for the model to reason about, not raw DB rows.
    """
    global call_count
    call_count += 1

    user_prompt = json.dumps({"evidence": evidence, "candidates": candidates}, indent=2)
    resp = _client.chat.completions.create(
        model=OPENROUTER_MODEL,
        messages=[
            {"role": "system", "content": JUDGMENT_SYSTEM_PROMPT},
            {"role": "user", "content": user_prompt},
        ],
        temperature=0,
    )
    raw = resp.choices[0].message.content.strip()
    # Models sometimes wrap JSON in fences despite instructions; strip them.
    if raw.startswith("```"):
        raw = raw.strip("`")
        if raw.startswith("json"):
            raw = raw[4:]
    try:
        return json.loads(raw)
    except json.JSONDecodeError:
        return {
            "decision": "escalate",
            "matched_ref": None,
            "matched_content_type": None,
            "confidence": 0.0,
            "reasoning": f"Could not parse model output as JSON: {raw[:200]!r}",
        }
